dist: trusty
sudo: required

env:
  - TERRAFORM_VERSION=0.12.3

# Fetch terraform
before_install:
  - curl -sLo terraform.zip https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
  - unzip terraform.zip
  - mkdir -p ~/bin
  - mv terraform ~/bin
  - export PATH="~/bin:$PATH"

script:
  - terraform fmt -check infrastructure
