dist: trusty
sudo: false
language: ruby
rvm:
  - 2.4.1
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
#cache: bundler
env:
  - TERRAFORM_VERSION=0.12.3 NOKOGIRI_USE_SYSTEM_LIBRARIES=true TF_LOG=trace

before_install:
  # Install terraform
  - curl -sLo terraform.zip https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
  - unzip terraform.zip
  - mkdir -p ~/bin
  - mv terraform ~/bin
  - export PATH="~/bin:$PATH"

  # Update to Bundler 2.0
  - gem update --system
  - gem install bundler

script:
  # Run Terraform
  - cd infrastructure
  - terraform fmt -check
  - terraform init
  - terraform apply -auto-approve

  # Run Jekyll
  - cd .. && cd src
  - bundle install
  - jekyll build

branches:
  only:
    - master
